import NavBar from "@/components/NavBar";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import { SkeletonTheme } from 'react-loading-skeleton';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  weight: '200',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
        <SkeletonTheme baseColor="#E0E0E0" highlightColor="#525252" duration={3}>
          <div className="container">
            <NavBar />
            <Toaster position="top-right" />
            {children}
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
